
services:
  ecommerce:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce
    ports:
      - "8080:8080"
    environment:
      DB_HOST: ecommerce_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: ecommerce
      PORT: 8080
      SALT: 10
    depends_on:
      ecommerce_db:
        condition: service_healthy

  ecommerce_db:
    image: postgres:16
    container_name: ecommerce_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

